// A car's drivetrain page (<slug>/drivetrain/). The page is static HTML generated by
// acr-setup-engineer's export_car_data.py; this module only runs the theme toggle and the
// tracking: the promo links, and one event when the reader scrolls to "How we worked it out".

import './theme.js';
import { track } from './tracking.js';

export const WORKINGS_EVENT = 'read-drivetrain-workings';

// The observed block is the section's heading, caption and first paragraph, so the event means
// they were on screen. Most of it has to be visible, not a sliver at the bottom edge.
export const WORKINGS_THRESHOLD = 0.6;

const windowScroll = fn => {
  globalThis.addEventListener?.('scroll', fn, { passive: true });
  return () => globalThis.removeEventListener?.('scroll', fn);
};

/**
 * Fire `event` once, when `target` is at least WORKINGS_THRESHOLD visible AND the reader has
 * scrolled. On a tall desktop screen the section can sit above the fold at load, and a page
 * that was only opened has not been read. Then stop watching.
 *
 * `Observer` is IntersectionObserver in the page and a fake in tests; `onScroll(fn)` subscribes
 * to scrolling and returns an unsubscribe. Without an observer (a very old browser) nothing is
 * tracked. Returns the observer, or null.
 */
export function watchWorkings(target, { Observer = globalThis.IntersectionObserver,
  send = track, event = WORKINGS_EVENT, onScroll = windowScroll } = {}) {
  if (!target || typeof Observer !== 'function') return null;
  let visible = false;
  let scrolled = false;
  let done = false;
  let unsubscribe = null;
  const maybeFire = () => {
    if (done || !visible || !scrolled) return;
    done = true;
    send(event);
    observer.disconnect();
    unsubscribe?.();
  };
  const observer = new Observer(entries => {
    const last = entries[entries.length - 1];
    // the browser reports the crossing ratio rounded, a hair under the threshold at times
    visible = Boolean(last?.isIntersecting && last.intersectionRatio >= WORKINGS_THRESHOLD - 0.01);
    maybeFire();
  }, { threshold: WORKINGS_THRESHOLD });
  unsubscribe = onScroll(() => {
    scrolled = true;
    maybeFire();
  });
  observer.observe(target);
  return observer;
}

if (typeof document !== 'undefined') {
  const head = document.querySelector('.workhead');
  watchWorkings(head, { event: head?.dataset.event || WORKINGS_EVENT });
  for (const link of document.querySelectorAll('a[data-track]')) {
    link.addEventListener('click', () => track(link.dataset.track));
  }
}
