// Light or dark. The colours live in app.css; this module only decides which set is in
// force, handles the header toggle and tells the page when the theme changes.
//
// With no stored choice the page follows the OS through prefers-color-scheme, CSS alone.
// A stored choice is applied before first paint by the inline script in each page's
// <head>, which sets <html data-theme>. The key below must match that script, which is
// generated by acr-setup-engineer's export_car_data.py (test/theme.test.js checks).

export const STORAGE_KEY = 'acr-car-lab-theme';

const root = () => document.documentElement;
const osQuery = () => window.matchMedia('(prefers-color-scheme: dark)');
const osTheme = () => (osQuery().matches ? 'dark' : 'light');

/** The theme actually showing: a forced one, otherwise the OS's. */
export function currentTheme() {
  const forced = root().dataset.theme;
  return forced === 'dark' || forced === 'light' ? forced : osTheme();
}

/**
 * The toggle's accessible name: the action, where the visible word is only the target.
 * It contains that visible word, so speech input can still say "click Dark".
 */
export const toggleLabel = theme =>
  (theme === 'dark' ? 'Switch to light theme' : 'Switch to dark theme');

const listeners = new Set();
let shown = null;

const button = () => document.querySelector('.theme');

function notify() {
  const theme = currentTheme();
  if (theme === shown) return;
  shown = theme;
  button()?.setAttribute('aria-label', toggleLabel(theme));
  for (const fn of listeners) fn(theme);
}

/** Called with the new theme whenever it changes, by the toggle or by the OS. */
export function onThemeChange(fn) {
  listeners.add(fn);
}

/**
 * Show `theme`. Picking the theme the OS already asks for drops the override, so two
 * clicks put the page back to following the OS rather than pinning it.
 */
export function setTheme(theme) {
  const follow = theme === osTheme();
  if (follow) delete root().dataset.theme;
  else root().dataset.theme = theme;
  try {
    if (follow) localStorage.removeItem(STORAGE_KEY);
    else localStorage.setItem(STORAGE_KEY, theme);
  } catch {
    // storage blocked (private mode, disabled cookies): the choice lasts for this page
  }
  notify();
}

if (typeof document !== 'undefined') {
  shown = currentTheme();
  button()?.setAttribute('aria-label', toggleLabel(shown));
  // Only changes what shows when nothing is forced; a forced theme ignores the OS.
  osQuery().addEventListener('change', notify);
  button()?.addEventListener('click', () =>
    setTheme(currentTheme() === 'dark' ? 'light' : 'dark'));
}
