import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { ISSUES, PROMO, dataLine } from '../js/footer.js';

test('the data line names the game version and the build date', () => {
  assert.equal(dataLine({ game_version: '0.6', generated: '2026-09-12' }),
               'Read from the ACR 0.6 game files. Generated 2026-09-12.');
});

test('a missing version or date drops that part and never prints undefined', () => {
  assert.equal(dataLine({ generated: '2026-09-12' }),
               'Read from the ACR game files. Generated 2026-09-12.');
  assert.equal(dataLine({ game_version: '0.6' }), 'Read from the ACR 0.6 game files.');
  assert.equal(dataLine({}), 'Read from the ACR game files.');
  assert.equal(dataLine(undefined), 'Read from the ACR game files.');
  assert.equal(dataLine({ game_version: null, generated: '' }), 'Read from the ACR game files.');
});

test('the promo line is the approved copy, with the skill name as the link', () => {
  assert.equal(PROMO.before + PROMO.link + PROMO.after,
    'Want a setup, not just the numbers? ACR Setup Engineer — a free Claude skill that '
    + 'tunes a car to how you drive and saves it to your Notion.');
  assert.equal(PROMO.link, 'ACR Setup Engineer');
  assert.equal(PROMO.href, 'https://github.com/fredmayor88/acr-setup-engineer');
});

test('the issues link follows the promo line on the same line, with a plain separator', () => {
  assert.equal(ISSUES.before, ' · ');
  assert.equal(ISSUES.link, 'Issues and feedback');
  assert.equal(ISSUES.href, 'https://github.com/fredmayor88/acr-car-lab/issues');
});

test('the picker footer says the same as the car page footer', () => {
  // index.html is generated by the exporter; this catches the two copies drifting apart
  const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
  const line = `<p class="promo">${PROMO.before}<a href="${PROMO.href}">${PROMO.link}</a>`
    + `${PROMO.after}${ISSUES.before}<a href="${ISSUES.href}">${ISSUES.link}</a></p>`;
  assert.ok(html.includes(line), 'picker promo line');
  assert.doesNotMatch(html, /target=/);
});

test('car pages track clicks on the issues link as click-issues', () => {
  // app.js builds the footer in the DOM, so this checks the wiring in its source
  const src = readFileSync(new URL('../js/app.js', import.meta.url), 'utf8');
  assert.match(src, /h\('a', \{ href: ISSUES\.href, onclick: \(\) => track\('click-issues'\) \}, ISSUES\.link\)/);
});

test('car pages track rev ceiling edits as edit-rev-ceiling, with named step buttons', () => {
  const src = readFileSync(new URL('../js/app.js', import.meta.url), 'utf8');
  assert.match(src, /'edit-rev-ceiling'/);
  // the step buttons are named from the noun: "Lower rev ceiling by 100 rpm" and "Raise …"
  assert.match(src, /noun: 'rev ceiling'/);
  assert.match(src, /`Lower \$\{noun\} by 100 rpm`/);
  assert.match(src, /`Raise \$\{noun\} by 100 rpm`/);
});

test('car pages send no car-<slug> event on load: GoatCounter already counts the page view', () => {
  const src = readFileSync(new URL('../js/app.js', import.meta.url), 'utf8');
  assert.doesNotMatch(src, /track\(\s*['"`]car-/);
});

test('the rev limit note says where the limit came from, then how to change it', async () => {
  const { revLimitNote } = await import('../js/footer.js');
  assert.equal(revLimitNote('measured'),
    'Measured in game with telemetry. If your limiter differs, edit it here.');
  assert.equal(revLimitNote('estimated'),
    'Estimated from the game files, not yet measured. If your limiter differs, edit it here.');
  assert.equal(revLimitNote('measured-stale'),
    'Measured on an earlier game version. If your limiter differs, edit it here.');
  assert.equal(revLimitNote(undefined), 'If your limiter differs, edit it here.');
});

test('the factor note names the cars it was fitted on, from the index', async () => {
  const { factorNote } = await import('../js/footer.js');
  const { readFileSync } = await import('node:fs');
  const index = JSON.parse(readFileSync(new URL('../data/index.json', import.meta.url), 'utf8'));
  assert.equal(factorNote(index),
    'A loaded tyre rolls on a smaller radius than the stored one. This factor was fitted against '
    + 'measured in-game top speeds on eight cars (Stratos, 306 Maxi, Xsara WRC, 037, 206 WRC, '
    + 'Delta Integrale, Impreza, GTA Junior), and is applied to every car and surface. Edit it and '
    + 'every chart redraws.');
  assert.equal(factorNote({ fit: { runs: 2, cars: ['A', 'B'] } }).includes('on two cars (A, B),'), true);
  assert.equal(factorNote({}), 'A loaded tyre rolls on a smaller radius than the stored one. This '
    + 'factor was fitted against measured in-game top speeds, and is applied to every car and '
    + 'surface. Edit it and every chart redraws.');
  assert.equal(factorNote(undefined), factorNote({}));
});

test('the index fit is the cars of the speed runs in calibration.json, in order', async (t) => {
  const { readFileSync, existsSync } = await import('node:fs');
  const cal = new URL('../../acr-setup-engineer/tools/gearing-charts/calibration.json', import.meta.url);
  if (!existsSync(cal)) { t.skip('no ../acr-setup-engineer checkout next to this repo'); return; }
  const runs = JSON.parse(readFileSync(cal, 'utf8')).speed_runs;
  const { fit } = JSON.parse(readFileSync(new URL('../data/index.json', import.meta.url), 'utf8'));
  assert.equal(fit.runs, runs.length);
  assert.equal(fit.cars.length, new Set(runs.map(r => r.car)).size);
});

test('the README states the fit the index carries', async () => {
  const { readFileSync } = await import('node:fs');
  const readme = readFileSync(new URL('../README.md', import.meta.url), 'utf8').replace(/\s+/g, ' ');
  const { fit } = JSON.parse(readFileSync(new URL('../data/index.json', import.meta.url), 'utf8'));
  const words = ['no', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten'];
  assert.ok(readme.includes(`on ${fit.runs} runs across ${words[fit.cars.length]} cars`));
  for (const stale of words.filter((_, i) => i !== fit.cars.length)) {
    assert.doesNotMatch(readme, new RegExp(`across ${stale} cars|on ${stale} cars`));
  }
});
