import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { ISSUES, PROMO, dataLine } from '../js/footer.js';

test('the data line names the game version and the build date', () => {
  assert.equal(dataLine({ game_version: '0.6', generated: '2026-09-12' }),
               'Read from the ACR 0.6 game files. Generated 2026-09-12.');
});

test('a missing version or date drops that part and never prints undefined', () => {
  assert.equal(dataLine({ generated: '2026-09-12' }),
               'Read from the ACR game files. Generated 2026-09-12.');
  assert.equal(dataLine({ game_version: '0.6' }), 'Read from the ACR 0.6 game files.');
  assert.equal(dataLine({}), 'Read from the ACR game files.');
  assert.equal(dataLine(undefined), 'Read from the ACR game files.');
  assert.equal(dataLine({ game_version: null, generated: '' }), 'Read from the ACR game files.');
});

test('the promo line is the approved copy, with the skill name as the link', () => {
  assert.equal(PROMO.before + PROMO.link + PROMO.after,
    'Want a setup, not just the numbers? ACR Setup Engineer — a free Claude skill that '
    + 'tunes a car to how you drive and saves it to your Notion.');
  assert.equal(PROMO.link, 'ACR Setup Engineer');
  assert.equal(PROMO.href, 'https://github.com/fredmayor88/acr-setup-engineer');
});

test('the issues link follows the promo line on the same line, with a plain separator', () => {
  assert.equal(ISSUES.before, ' · ');
  assert.equal(ISSUES.link, 'Issues and feedback');
  assert.equal(ISSUES.href, 'https://github.com/fredmayor88/acr-car-lab/issues');
});

test('the picker footer says the same as the car page footer', () => {
  // index.html is generated by the exporter; this catches the two copies drifting apart
  const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
  const line = `<p class="promo">${PROMO.before}<a href="${PROMO.href}">${PROMO.link}</a>`
    + `${PROMO.after}${ISSUES.before}<a href="${ISSUES.href}">${ISSUES.link}</a></p>`;
  assert.ok(html.includes(line), 'picker promo line');
  assert.doesNotMatch(html, /target=/);
});

test('car pages track clicks on the issues link as click-issues', () => {
  // app.js builds the footer in the DOM, so this checks the wiring in its source
  const src = readFileSync(new URL('../js/app.js', import.meta.url), 'utf8');
  assert.match(src, /h\('a', \{ href: ISSUES\.href, onclick: \(\) => track\('click-issues'\) \}, ISSUES\.link\)/);
});

test('car pages track rev ceiling edits as edit-rev-ceiling, with named step buttons', () => {
  const src = readFileSync(new URL('../js/app.js', import.meta.url), 'utf8');
  assert.match(src, /'edit-rev-ceiling'/);
  // the step buttons are named from the noun: "Lower rev ceiling by 100 rpm" and "Raise …"
  assert.match(src, /noun: 'rev ceiling'/);
  assert.match(src, /`Lower \$\{noun\} by 100 rpm`/);
  assert.match(src, /`Raise \$\{noun\} by 100 rpm`/);
});
